### ISSUE TITLE
Device not implemented: HmIP-SRH - Fenstergriffsensor via type ROTARY_HANDLE_SENSOR

### ISSUE THREAD

**Issue by MaxiKingXXL** [marcsowen/homebridge-homematicip#16]
Would be nice if the window handle sensor could be added.

Thanks

**Comment by marcsowen** [comment]
What device type is showing up in the logs? ROTARY_HANDLE_SENSOR? And what is the product name? HMIP-SRH? I will try to find time this weekend.

**Comment by MaxiKingXXL** [comment]
Yes, the device type shows ROTARY_HANDLE_SENSOR. Product name is: Homematic IP Fenstergriffsensor. Device type is HmIP-SRH

Sounds great, just let me know if you need any additional info.

Status can be OPEN, CLOSED or TILTED

**Comment by marcsowen** [comment]
Can you try version 0.0.13? It should work now, but since I don't own the device, I cannot test it. Feedback is appreciated! :)

TILTED is not supported by the HomeKit contact sensor. TILTED will be treated as open by the plugin.

**Comment by MaxiKingXXL** [comment]
I still get the same error message after I made the update:

[23.1.2021, 14:23:19] Loaded plugin: homebridge-homematicip@0.0.13
...
[23.1.2021, 14:23:28] [HomematicIP] Device not implemented: HmIP-SRH - Fenstergriffsensor via type ROTARY_HANDLE_SENSOR

Can you take another look please?

**Comment by MaxiKingXXL** [comment]
The official english name from Homematic is:  "Homematic IP Window Handle Sensor"

**Comment by marcsowen** [comment]
Argh... sorry! Stupid typo. Try again with 0.0.14. Thanks.

**Comment by MaxiKingXXL** [comment]
Cool, works now!

Thanks for fixing it that quick!
